apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: helloworld-nodejs
spec:
  template:
    spec:
      containers:
        - image: docker.io/osilkin/helloworld-nodejs
          env:
            - name: TARGET
              value: "Node.js Sample v1"
