name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: "Test the repo"

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Fetch
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Project
        run: npm install
      - name: Run Unit Tests & Generate Coverage
        run: npm coverage
      - name: Upload coverage data
        uses: codecov/codecov-action@v2
        with:
          files: ./coverage/lcov.info
          verbose: true
          fail_ci_if_error: true

